name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ./report/report.tex
      - name: Upload pdf
        uses: actions/upload-artifact@v2
        with:
           name: PDF
           path: ./report.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'v0.0.1')
        with:
          files: report.pdf
